### ISSUE TITLE
Error is thrown when JSON can't be resolved.

### ISSUE THREAD

**Issue by mielvds** [SDM-TIB/SDM-RDFizer#52]
**Describe the bug**
Rdfizer throws exception when a JSON path returns null, while the triple(s) shouldn't generate. That said, the following example shouldn't even return null and simply work (works in RMLMapper)

```
TM: http://example.org/tm/json
Traceback (most recent call last):
  File "/Users/mielvandersande/.pyenv/versions/3.8.7/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/mielvandersande/.pyenv/versions/3.8.7/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mielvandersande/.pyenv/versions/3.8.7/lib/python3.8/site-packages/rdfizer/__main__.py", line 44, in <module>
    semantify(config_path)
  File "/Users/mielvandersande/.pyenv/versions/3.8.7/lib/python3.8/site-packages/rdfizer/__init__.py", line 3818, in semantify
    number_triple += executor.submit(semantify_file, triples_map, triples_map_list, ",",output_file_descriptor, wr, config[dataset_i]["name"], data).result()
  File "/Users/mielvandersande/.pyenv/versions/3.8.7/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/mielvandersande/.pyenv/versions/3.8.7/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/mielvandersande/.pyenv/versions/3.8.7/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/mielvandersande/.pyenv/versions/3.8.7/lib/python3.8/site-packages/rdfizer/__init__.py", line 2153, in semantify_file
    elif "IRI" in predicate_object_map.object_map.term:
TypeError: argument of type 'NoneType' is not iterable
```

**To Reproduce**

``` json
[
    {"id": "001", "name": "x"},
    {"id": "002", "name": "y"},
    {"id": "003", "name": "z"}
]
```

```
@prefix rr:         <http://www.w3.org/ns/r2rml#> .
@prefix foaf:       <http://xmlns.com/foaf/0.1/> .
@prefix ex:         <http://example.com/> .
@prefix xsd:        <http://www.w3.org/2001/XMLSchema#> .
@prefix rml:        <http://semweb.mmlab.be/ns/rml#> .
@prefix ql:         <http://semweb.mmlab.be/ns/ql#> .
@prefix org:        <http://www.w3.org/ns/org#> .
@prefix skos:       <http://www.w3.org/2004/02/skos/core#> .
@prefix dc:         <http://purl.org/dc/terms/> .
@base               <http://example.org/tm/> .


<json>
  a rr:TriplesMap;
    
  rml:logicalSource [
    rml:source "debug/data.json";
    rml:referenceFormulation ql:JSONPath;
    rml:iterator "$[*]"
  ];
  rr:subjectMap [
    rr:template "http://example.org/{id}";
    rr:class org:Organization
  ]; 
  rr:predicateObjectMap [ 
    rr:predicate skos:altLabel; 
    rr:objectMap [ rml:reference "name"; rr:language "nl" ]
  ].
```

**Expected behavior**
Should generate

```
<http://example.org/001> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Organization>.
<http://example.org/001> <http://www.w3.org/2004/02/skos/core#altLabel> "x"@nl.
<http://example.org/002> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Organization>.
<http://example.org/002> <http://www.w3.org/2004/02/skos/core#altLabel> "y"@nl.
<http://example.org/003> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Organization>.
<http://example.org/003> <http://www.w3.org/2004/02/skos/core#altLabel> "z"@nl.
```

**Desktop (please complete the following information):**
 - OS: OSX ARM-64
 - Python: 3.8.7 with pyenv

**Comment by eiglesias34** [comment]
Hello,

I fixed the issue. I got the same expected result. Please note that the changes I made were to the source code and not to the library. For the time being, please use run_rdfizer.py to execute the SDM-RDFizer. Please test it so we can close this issue.

Thank you for using the SDM-RDFizer.

**Comment by mielvds** [comment]
Sorry, not done yet. The specific example now works with `run_rdfizer.py`, thanks for that! However, JSONPaths that don't resolve still throw an error. 

New example:
```json
[
  {
    "id": "001",
    "name": "x",
    "custom_fields": [
      {
        "value": "OR-12345",
        "label": "OR-ID"
      }
    ]
  },
  {
    "id": "002",
    "name": "y",
    "custom_fields": [
      {
        "value": "OR-6789",
        "label": "OR-ID"
      }
    ]
  },
  {
    "id": "003",
    "name": "z",
    "custom_fields": [
      {
        "value": "OR-1011",
        "label": "OR-ID"
      }
    ]
  }
]

```
mapping:
```
@prefix rr:         <http://www.w3.org/ns/r2rml#> .
@prefix foaf:       <http://xmlns.com/foaf/0.1/> .
@prefix ex:         <http://example.com/> .
@prefix xsd:        <http://www.w3.org/2001/XMLSchema#> .
@prefix rml:        <http://semweb.mmlab.be/ns/rml#> .
@prefix ql:         <http://semweb.mmlab.be/ns/ql#> .
@prefix org:        <http://www.w3.org/ns/org#> .
@prefix skos:       <http://www.w3.org/2004/02/skos/core#> .
@prefix dc:         <http://purl.org/dc/terms/> .
@base               <http://example.org/tm/> .


<json>
  a rr:TriplesMap;
    
  rml:logicalSource [
    rml:source "debug/data.json";
    rml:referenceFormulation ql:JSONPath;
    rml:iterator "$[*]"
  ];
  rr:subjectMap [
    rr:template "http://example.org/{custom_fields[?(@.label=='OR-ID')].value}";
    rr:class org:Organization
  ]; 
  rr:predicateObjectMap [ 
    rr:predicate skos:altLabel; 
    rr:objectMap [ rml:reference "name"; rr:language "nl" ]
  ].
```
produces

```
TM: http://example.org/tm/json
Traceback (most recent call last):
  File "/Users/mielvandersande/Tools/SDM-RDFizer/rdfizer/run_rdfizer.py", line 3, in <module>
    semantify(str(sys.argv[1]))
  File "/Users/mielvandersande/Tools/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 4117, in semantify
    number_triple += executor.submit(semantify_file, triples_map, triples_map_list, ",",output_file_descriptor, wr, config[dataset_i]["name"], data).result()
  File "/Users/mielvandersande/.pyenv/versions/3.8.7/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/mielvandersande/.pyenv/versions/3.8.7/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/mielvandersande/.pyenv/versions/3.8.7/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/mielvandersande/Tools/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 2007, in semantify_file
    subject_value = string_substitution(triples_map.subject_map.value, "{(.+?)}", row, "subject", ignore, triples_map.iterator) 
  File "/Users/mielvandersande/Tools/SDM-RDFizer/rdfizer/rdfizer/functions.py", line 276, in string_substitution
    if re.search("^[\s|\t]*$", row[match]) is None:
  File "/Users/mielvandersande/.pyenv/versions/3.8.7/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

Note that `$[*].custom_fields[?(@.label=='OR-ID')].value` should work according to https://jsonpath.com/

**Comment by eiglesias34** [comment]
Hello again,

I was able to fix the issue. I got this as the output:
`<http://example.org/OR-12345> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Organization>.
<http://example.org/OR-12345> <http://www.w3.org/2004/02/skos/core#altLabel> "x"@nl.
<http://example.org/OR-6789> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Organization>.
<http://example.org/OR-6789> <http://www.w3.org/2004/02/skos/core#altLabel> "y"@nl.
<http://example.org/OR-1011> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Organization>.
<http://example.org/OR-1011> <http://www.w3.org/2004/02/skos/core#altLabel> "z"@nl.`

Previously the SDM-RDFizer didn't take into consideration conditions when processing data. Currently, the SDM-RDFizer processes only one occurrence of the value that fulfills the condition. I will expand it at a later date. 

Thank you again for using the SDM-RDFizer.

**Comment by mielvds** [comment]
Thx, it does produce output now. However, it now produces urls like `<http://example.org/{custom_fields[?(@.label=='OR-ID')].value}>` when the result is null.

**Comment by eiglesias34** [comment]
Hello,

I fixed the issue. None are being correctly verified now.

**Comment by mielvds** [comment]
Yes, works now! keep up the good work!

**Comment by mielvds** [comment]
I have to reopen this. It seems you fix broke the first example I gave. This doesn't produce any triples anymore.

**Comment by dachafra** [comment]
We are working in order to integrate the running of the rml-test-cases for each new update of the code, thanks for the recommendation @mielvds!

**Comment by eiglesias34** [comment]
I fixed the issue. I test it out with all three cases and everything works.

**Comment by mielvds** [comment]
> We are working in order to integrate the running of the rml-test-cases for each new update of the code, thanks for the recommendation @mielvds!

That's great to hear @dachafra ! Unfortunately, the current test cases woudln't cover the issues caused by the referenceFormulation implementation. This would be an interesting  extension for the KG construct CG to work on (I already had a short discussion about that here: https://github.com/RMLio/rml-test-cases/issues/35). I hope I can find some time to contribute to the group soon. 

@eiglesias34 everything works now. Thanks!

**Comment by dachafra** [comment]
@mielvds looking forward to working with you on the definition of the new test-cases!
